import { spawn } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import puppeteer from 'puppeteer-core';
const port = 7890 + Math.floor(Math.random() * 50);
const dataDir = fs.mkdtempSync(os.tmpdir() + '/ao-ui-');
const server = spawn(process.execPath, ['server/index.js'], { env: { ...process.env, AO_PORT: String(port), AO_DATA_DIR: dataDir, AO_GUIDE_FAKE: '1', OPENAI_API_KEY: 'x' }, stdio: 'ignore' });
await new Promise((r) => setTimeout(r, 1500));
const base = `http://127.0.0.1:${port}`;
await fetch(base + '/api/settings', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ guideProvider: 'fake', guideModels: { 'openai-api': 'gpt-5.5-mini' } }) });
const browser = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome', args: ['--no-sandbox'] });
const page = await browser.newPage();
await page.setViewport({ width: 1200, height: 900 });
page.on('console', (m) => m.type() === 'error' && console.log('console error:', m.text()));
page.on('pageerror', (e) => console.log('pageerror:', e.message));
await page.goto(base + '/?view=guide');
await new Promise((r) => setTimeout(r, 1500));
await page.type('#view-guide textarea', 'hola');
await page.keyboard.press('Enter');
await new Promise((r) => setTimeout(r, 1500));
await page.screenshot({ path: '/tmp/ft8-chat.png' });
await fetch(base + '/api/settings', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ guideProvider: 'openai-api' }) });
await new Promise((r) => setTimeout(r, 500));
await page.click('[data-action=settings]');
await new Promise((r) => setTimeout(r, 1000));
await page.evaluate(() => document.querySelector('select[name=guideProvider]').scrollIntoView());
await page.screenshot({ path: '/tmp/ft8-settings.png' });
await browser.close();
server.kill();
fs.rmSync(dataDir, { recursive: true, force: true });
